# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Lottie_objc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lottie_objc
  pod 'lottie-ios', '2.5.3'
end
